# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Võ Văn Đức
title: Developer - DevOps
email: vovanduc1989@gmail.com
website: vovanduc.github.io/resume
phone: 0937.366.388

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: leebin89
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: vovanduc
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/me.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name's Duc and I'm a developer and delivered high-end website solutions to a diverse client base by utilizing wide-ranging technologies and frameworks.

  Knowledge of AWS service (EC2, S3, CloudFront).
content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.
  
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Vinacis Group
        link: vinacis.com
        sub_title: Junior DevOps
        caption:  January 2021 - August 2021
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          <b>Developing CI/CD roadmap and implementing to the project</b>






      - layout: left
        title: Vinacis Group
        link: vinacis.com
        sub_title: Software Developer
        caption: August 2017 - January 2021
        quote: >
          Cloud Computing: Company providing server infrastructure and cloud computing solutions
        description: | # this will include new lines to allow paragraphs
          -  Develop and improve integrations with CRMmini internal
          -  Design and develop page customer portal system to help customers manage their account
          -  Create, maintains and enhances existing custom API for provider cloud (Onapp, Virtuozzo, Plesk)
          -  To support development manager in solution delivery and implementation

      - layout: left
        title: Go Digital World
        #link:
        #link_text:
        sub_title: Web Application Developer
        caption: January 2014 - January 2016
        quote: >
          Project Order Product from Amazon.com: Customers in my country can buy products from Amazon.com Take a leading role in all stages of the software development lifecycle including requirements development, UI and database schema design, programming, system and user acceptance testing
        description: | # this will include new lines to allow paragraphs
            <b>How to Scrape Amazon.com</b>
            - Build an Amazon scraper for extracting product details and pricing when customer request (curl)
            - Scraping essentially means that script will download the web page from Amazon, parse the HTML and extract the price
            - Avoiding bot detection, use a proxy Service

            <b>Order System Admin</b>
            - Module manage customer, order, invoice, product
            - Role manage for each module
            - Data visualizations, ad-hoc reports, database extracts, as well as Data visualizations, ad-hoc reports, database extracts, as well as
            - Multi website for each brand name

            <b>Customer Portal</b>
            - Customer can access wesite, research product, add to cart and payment
            - Manage invoice, check status order
            
      - layout: left
        title: Nhan Hoa Software
        link: nhanhoa.com
        # link_text: boringcompany.com
        sub_title: Web Application Developer
        caption: January 2011 - January 2014
        quote: >
          Project Website Builder: The platform that gives customer the freedom to pick a template and customize theme. Start customer own blog, add an online store. Customers must purchase premium packages in order to connect their sites to their customer domains, theme pro, add e-commerce capabilities, or buy extra data storage and bandwidth
        description: | # this will include new lines to allow paragraphs
            - Develop and deploy new features to existing products
            - Write documentation to describe application development logic and coding
            - Collaborate with sales teams to understand customer requirements and provide sales support
            - Maintaining websites for clients
            - Multi-DB (one system database and separated tenant databases, table prefixed in the system database)
            - Multi-Channel (theme, subdomain for each tenant)      

  - title: Skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      - <b>Cloud Native: </b> Kubernetes - AWS
      - <b>Infrastructure as Code: </b> Ansible - Terraform
      - <b>Monitoring - Logging: </b> Prometheus - Fluentd - Grafana - Elasticsearch
      - <b>CI/CD: </b> Gitlab
      - <b>Scripting and Coding: </b> JavaScript - PHP - Python - SQL - Git - YAML
      - <b>Web frameworks: </b> Laravel - Codeigniter - Django
      - <b>Tools: </b> Docker - Virtualbox - Vagrant - Visual Studio Code - Iterm 

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: center
        title: 
        caption: 2008  —  2010
        sub_title: Software Engineering
        #quote: >
        description: | # this will include new lines to allow paragraphs
            DNIIT (Professional Diploma in Information Technology)

            NIIT Edufirst Centre, Ho Chi Minh, Vietnam

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
